
- name: put nodes in hostfile on virtual test machines
  lineinfile:
    dest=/etc/hosts
    line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{ item }}"
    state=present
  with_items:
   - "{{ groups['controller'] }}"
   - "{{ groups['workers'] }}"
  when: test_or_real == "test"

- name: put nodes in hostfile
  lineinfile:
    dest=/etc/hosts
    line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state=present
  with_items:
   - "{{ groups['controller'] }}"
   - "{{ groups['workers'] }}"
  when: test_or_real == "real"


#- name: set hostname
#  hostname:
#    name: "{{ inventory_hostname }}"
